---
title: "PaleoFidelity"
author: "Michal Kowalewski"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PaleoFidelity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction

PaleoFidelity package is aimed at users interested in conservation paleobiology, taphonomy, and paleoecology. The functions provided in this package compute common measures of fidelity (live-dead agreement) for community data. The package is designed specifically for abundance community data and provides a platform for relational analyses of multiple datasets and factors. The primary applications of PaleoFidelity are as follows:

FUNCTION __FidelityEst__ Compute common measures of fidelity (correlation coefficients and similarity measures)

FUNCTION __FidelityAlpha__ Computes live-dead offsets in alpha diversity/evenness 

FUNCTION __FidelityBeta__ Computes live-dead offsets in beta diversity

Each of the above functions includes a companion function that implements resampling tests to evaluate statistical significance of the observed statistics and/or calculate bootstrap confidence intervals.

A detailed discussion of individual functions and practical examples are provided below.
